NationalParkWEBAPP/Controllers/NationalParkController.cs
using Microsoft.AspNetCore.Mvc;
using NationalParkWEBAPP.Models;
using NationalParkWEBAPP.Repository.IRepository;
using NationalParkWEBAPP;

namespace NationalParkWebApp.Controllers
{
    public class NationalParkController : Controller
    {
        private readonly INationalParkRepository _nationalParkRepository;
        public NationalParkController(INationalParkRepository nationalParkRepository)
        {
            _nationalParkRepository = nationalParkRepository;

        }
        #region APIs
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var nationalParkList = await _nationalParkRepository.GetAllAsync(SD.NationalParkAPIPath);
            return Json(new { data = nationalParkList });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _nationalParkRepository.DeleteAsync(SD.NationalParkAPIPath, id);
            if (status)
                return Json(new { success = true, message = "Delete Data Successfully!!!" });
            return Json(new { success = false, message = "Something Went Wrong While Deleting Data!!!" });
        }

        #endregion
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            NationalPark nationalPark = new NationalPark();                      //Object Of Class
            if (id == null) return View(nationalPark);
            nationalPark = await _nationalParkRepository.GetAsync
                (SD.NationalParkAPIPath, id.GetValueOrDefault());
            return View(nationalPark);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(NationalPark nationalPark)
        {
            if (nationalPark == null) return BadRequest();
            if (!ModelState.IsValid) return BadRequest();
            //*****
            var files = HttpContext.Request.Form.Files;
            if (files.Count() > 0)
            {
                byte[] p1 = null;                                            // Byte is an Array
                using (var fs = files[0].OpenReadStream())
                {
                    using (var ms = new MemoryStream())                         //Using is uesd for Disposable Object
                    {
                        fs.CopyTo(ms);
                        p1 = ms.ToArray();
                    }
                }
                nationalPark.Picture = p1;
            }
            else
            {
                var nationalParkInDb = await _nationalParkRepository.GetAsync
                    (SD.NationalParkAPIPath, nationalPark.Id);
                nationalPark.Picture = nationalParkInDb.Picture;
            }
            if (nationalPark.Id == 0)
                await _nationalParkRepository.CreateAsync(SD.NationalParkAPIPath, nationalPark);
            else
                await _nationalParkRepository.UpdateAsync(SD.NationalParkAPIPath, nationalPark);
            return RedirectToAction(nameof(Index));
        }
    }
}

NationalParkWEBAPP/Controllers/TrailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NationalParkWEBAPP.Models;
using NationalParkWEBAPP.Models.ViewModels;
using NationalParkWEBAPP.Repository.IRepository;
using NationalParkWEBAPP;

namespace NationalParkWebApp.Controllers
{
    public class TrailController : Controller
    {
        private readonly INationalParkRepository _nationalparkRepository;
        private readonly ITrailRepository _trailRepository;
        public TrailController(INationalParkRepository nationalParkRepository, ITrailRepository trailRepository)
        {
            _nationalparkRepository = nationalParkRepository;
            _trailRepository = trailRepository;
        }
        #region APIs
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _trailRepository.GetAllAsync(SD.TrailAPIPath) });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var Status = await _trailRepository.DeleteAsync(SD.TrailAPIPath, id);
            if (Status)
                return Json(new
                {
                    success = true,
                    message = "Data Deleted Successfully !!!!"
                });
            return Json(new
            {
                success = false,
                message = "Something Went Wrong While Deleting Data!!!!"
            });
        }
        #endregion
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            var nationalParkList = await _nationalparkRepository.GetAllAsync(SD.NationalParkAPIPath);
            TrailVM trailVM = new TrailVM()
            {
                NationalParkList = nationalParkList.Select(nl => new SelectListItem()
                {
                    Text = nl.Name,
                    Value = nl.Id.ToString()
                }),
                Trail = new Trail()
            };
            if (id == null) return View(trailVM);
            trailVM.Trail = await _trailRepository.GetAsync(SD.TrailAPIPath, id.GetValueOrDefault());
            if (trailVM.Trail == null) return NotFound();
            return View(trailVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(TrailVM trailVM)
        {
            if (trailVM == null) return BadRequest();
            if (!ModelState.IsValid) return BadRequest();
            if (trailVM.Trail.Id == 0)
                await _trailRepository.CreateAsync(SD.TrailAPIPath, trailVM.Trail);
            else
                await _trailRepository.UpdateAsync(SD.TrailAPIPath, trailVM.Trail);
            return RedirectToAction(nameof(Index));

        }
    }
}

NationalParkWEBAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NationalParkWEBAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NationalParkWEBAPP.styles.css" asp-append-version="true" />
    @*CSS REF*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NationalParkWEBAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NationalPark" asp-action="Index">NationalPark</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trail" asp-action="Index">Trail</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - NationalParkWEBAPP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*JS REF*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js" integrity="sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>